### ISSUE TITLE
Xcode Version 13.1 (13A1030d),iphoneX 12.2 真机模拟报错

### ISSUE THREAD

**Issue by liuzhenhan** [ZXKitCode/ZXKitSwift#1]
我用cocopods导入 pod 'ZXKitSwift', '~> 0.1.0',在真机模拟的时候crash,控制太打印如下 

dyld: Library not loaded: /System/Library/Frameworks/CryptoKit.framework/CryptoKit
  Referenced from: /private/var/containers/Bundle/Application/3F8A4BXF-EC55-420E-846B-9D0245192BE9/xxx.app/Frameworks/ZXKitUtil.framework/ZXKitUtil
  Reason: image not found

**Comment by DamonHu** [comment]
应该是util判断版本问题，我现在修复一下，稍等

**Comment by DamonHu** [comment]
重新运行一下

```
pod update
```
把ZXKitUtil更新到3.2.3即可

**Comment by liuzhenhan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
